name: flutter_pangle_global_ads
description: "A professional Flutter advertising plugin for Pangle Global"
version: 1.0.0
homepage: https://global.flutterads.top
repository: https://github.com/FlutterAds/flutter_pangle_global_ads
issue_tracker: https://github.com/FlutterAds/flutter_pangle_global_ads/issues
documentation: https://global.flutterads.top
topics: [flutterads, ads, pangle, tiktok, income]
funding: [https://github.com/FlutterAds/.github]

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zero.flutter_pangle_global_ads
        pluginClass: FlutterPangleGlobalAdsPlugin
      ios:
        pluginClass: FlutterPangleGlobalAdsPlugin
